version: '3.7'

services:
  kairos-db:
    image: postgres:latest
    container_name: kairos-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=kairos
      - POSTGRES_USER=kairos_user
      - POSTGRES_PASSWORD=kairos_password
    volumes:
      - pgdata:/var/lib/postgresql/data
      - pgconf:/etc/postgresql
      - pglog:/var/log/postgresql


  karios-pgadmin:
    image: dpage/pgadmin4
    container_name: kairos-pgadmin4
    restart: always
    depends_on:
      - kairos-db
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user@kairos.com
      PGADMIN_DEFAULT_PASSWORD: kairos
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  kairos-api:
    image: kairos-api:dev
    container_name: kairos-api
    depends_on:
      - kairos-db
    build:
      context: kairos-api
      dockerfile: ./Dockerfile
    ports:
      - 5001:5001
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5001
      
  kairos-web:
    image: kairos-web:dev
    container_name: kairos-web
    restart: unless-stopped
    build:
      context: kairos-web
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    volumes:
      - ./kairos-web:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 4200:4200
      - 49153:49153

volumes:
  pgdata:
  pgconf:
  pglog:
  pgadmin-data:
