name: Test Docker Compose Debug 

on: [pull_request]

jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Start containers
      run: docker-compose -f "docker-compose.debug.yml" up -d --build

    - name: Stop containers
      if: always()
      run: docker-compose -f "docker-compose.debug.yml" down
